### ISSUE TITLE
Trouver des logos... 

### ISSUE THREAD

**Issue by dridk** [dridk/freebox-desktop#13]
Logos pour freebox desktop et pour chaques modules ? 
On prend les logos de free directement ?

**Comment by pasnox** [comment]
Je pense que c est le mieux

**Comment by dridk** [comment]
Voila un petit apercu... ptetre avec des couleurs ? vous en pensez quoi ? @pasnox @ikit 
![preview](https://f.cloud.github.com/assets/1911063/1013219/8f00daa6-0b81-11e3-897e-234c47df41de.png)

**Comment by dridk** [comment]
Avec un peu de couleurs... 

![preview2](https://f.cloud.github.com/assets/1911063/1013535/d05fb1ce-0b8c-11e3-98e1-0c9dff977c21.png)

**Comment by dridk** [comment]
Mode epuré... permet d'avoir des petits icones...
![preview3](https://f.cloud.github.com/assets/1911063/1013641/7a8661d4-0b92-11e3-9f59-4b5b4a5ca905.png)

**Comment by dridk** [comment]
Logo de freebox OS utilisé
