### ISSUE TITLE
deploy GIF 

### ISSUE THREAD

**Issue by dridk** [dridk/freebox-desktop#19]
Ajouté le dll pour le GIF

**Comment by ikit** [comment]
Je suppose que c'est pour ça que je n'ai pas vu ta superbe animation pour autoriser la connexion à ma freebox ?

**Comment by dridk** [comment]
Oui...  Tu créer un dossier imageformats/ ou se trouve ton executable . Et tu met dedans le fichier : 
qgif4.dll   que tu trouvera sur ton PC. genre le dossier Qt/   Fait une recherche .
