### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by dartcity** [dridk/freebox-desktop#24]
au lancement de l'application:

Runtime Error!

![screenshot001](https://f.cloud.github.com/assets/5636678/1287671/69449ad8-2ffc-11e3-98ad-065089919dbc.jpg)

**Comment by dridk** [comment]
correction manuel : Dans le dossier freebox-desktop : 
- crée un dossier platforms avec dedans qwindows.dll 
- crée un dossier imageformats avec dedans : qgif.dll qico.dll qjpeg.dll

Sinon, le setup est corrigé ! 
https://github.com/dridk/freebox-desktop/releases/download/v0.1-beta/setup.exe

**Comment by dridk** [comment]
En attente ... Ne plus jamais prendre le dossier platforms/ de Qtcreator !

**Comment by dartcity** [comment]
Merci hâte de tester!

**Comment by dridk** [comment]
Voila, je pense que cette version marche... enfin !
https://github.com/dridk/freebox-desktop/releases/download/v0.1-beta/setup.exe

2013/10/9 dartcity notifications@github.com

> Merci hâte de tester!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/dridk/freebox-desktop/issues/24#issuecomment-25956104
> .

## 

Sacha schutz
+33651571606
qt developer at labsquare
sacha@labsquare.org

**Comment by dartcity** [comment]
ca fonctionne!
