### ISSUE TITLE
Ip externe ne marche pas ?

### ISSUE THREAD

**Issue by Baloos** [dridk/freebox-desktop#34]
Bonjour,
j'essaye de me connecter à ma freebox avec ip externe fbx:port (autre que 80, car déjà utilisé par mon nas) et n'obtiens aucun résultat.. est-ce un bug ou ais-je râté quelquechose ?
D'avance merci et bravo pour cette belle et utile app.
Cordialement,
Baloo

**Comment by dridk** [comment]
Je vais tester ce soir. Est ce que freebox OS marche a distance ?

**Comment by Baloos** [comment]
Autant pour moi..

En fait : j’ai désactivé mon nas (port 80). Mis la fbx sur le port 80. M’y
suis connecté en local, ai autorisé l’app.

Et depuis, rebasculé la fbx sur le port 90, le nas sur 80,  l’app connectée
en ip externe sur le port 90 et ça marche nickel !

Merci !!!

Au fait, deux chtites corrections orthographiques /coquilles : Autoriser à
la place d’Auhoriser sur la console « gestion des fbx ». Lorsque la freebox
autorise l’app, celle-ci nous envoie un message « Autorisation réussi » (un
petit e à la fin de réussi)
